name: Deploy Frontend to Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查Git代码
        uses: actions/checkout@v2

      - name: 前置DockerBuild
        uses: docker/setup-buildx-action@v1

      - name: 登录阿里云Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USER_NAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: 构建Docker镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/bot0/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 连接远程服务器并部署
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull registry.cn-hangzhou.aliyuncs.com/bot0/frontend:latest
            docker stop my-frontend || true
            docker rm my-frontend || true
            docker run -d --name my-frontend -p 9001:80 registry.cn-hangzhou.aliyuncs.com/bot0/frontend:latest
